from learn2design.example_algorithms.adam_gd import AdamGD
from learn2design.example_algorithms.na_adam_gd import NAAdamGD
from learn2design.example_algorithms.optax_sgdm import OptaxSGDM
from learn2design.example_algorithms.scipy_bfgs import BFGS
from learn2design.example_algorithms.lbfgs_gd import LBFGSGD
from learn2design.example_algorithms.random_search import RandomSearch
from learn2design.example_algorithms.pycma_cmaes import PyCMACMAES
from learn2design.example_algorithms.solver import Solver